# Generated by Django 4.1.5 on 2023-05-16 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Пароль должен содержать не менее 8 символов и иметь по крайней мере одну строчную букву, одну заглавную букву и одну цифру!', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{8,}$')], verbose_name='Пароль')),
                ('age', models.DateField(verbose_name='год рождения')),
            ],
        ),
    ]
