# Generated by Django 4.2 on 2023-05-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
